general {
    lock_cmd         = pidof hyprlock || hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd  = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 10 min → lock
listener {
    timeout    = 600
    on-timeout = pidof hyprlock || hyprlock
}

# 15 min → monitor off (DPMS)
listener {
    timeout    = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}
